# Generated by Django 5.1.4 on 2025-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_job_title', models.CharField(max_length=50)),
                ('rating_count', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
